apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  # Generate a unique name for each run
  generateName: cd-notebook-controller-1234abcd
  labels:
    app: notebook-controller
    image_tag: vmaster-g1234abcd
    version: v1
spec:
  pipelineRef:
    name: ci-pipeline
  params:
  - name: "path_to_context"
    value: "components/notebook-controller"
  - name: "path_to_docker_file"
    value: "components/notebook-controller/Dockerfile"
  - name: "path_to_manifests_dir"
    value: "jupyter/notebook-controller"
  - name: "src_image_url"
    value: "gcr.io/kubeflow-images-public/notebook-controller"
  - name: "container_image"
    value: "gcr.io/kubeflow-releasing/update_kf_apps:d4b8243@sha256:656a4ad689b17715a287f09772cc48444a2190c353c5b84828db4fbf4ede4acc"
  resources:
  # The git resources that will be used
  - name: app-repo
    resourceSpec:
      type: git
      params:
        - name: revision
          value: "1234abcd"
        - name: url
          value: git@github.com:kubeflow/kubeflow.git
  - name: manifests
    resourceSpec:
      type: git
      params:
        - name: revision
          value: v1.0-branch
        - name: url
          value: git@github.com:kubeflow/manifests.git
  # TODO(jlewi): Replace with kubeflw/kubeflow once the PR is checked in.
  - name: ci-tools
    resourceSpec:
      type: git
      params:
        - name: revision
          value: cicd_delete_old_prs
        - name: url
          value: git@github.com:jlewi/testing.git
  # The image we want to build
  - name:  image
    resourceSpec:
      type: image
      params:
      - name: url
        value: gcr.io/kubeflow-images-public/notebook-controller:vmaster-g1234abcd
  serviceAccountName: ci-pipeline-run-service-account
