apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: kubeflow
      server: https://35.188.73.10
    k8sVersion: v1.7.0
    path: default
kind: ksonnet.io/app
libraries:
  core:
    gitVersion:
      commitSha: bb84329fd79c6dfead218c7348189df751700db6
      refSpec: v0.1.0-rc.2
    name: core
    registry: kubeflow
  tf-job:
    gitVersion:
      commitSha: bb84329fd79c6dfead218c7348189df751700db6
      refSpec: v0.1.0-rc.2
    name: tf-job
    registry: kubeflow
  tf-serving:
    gitVersion:
      commitSha: bb84329fd79c6dfead218c7348189df751700db6
      refSpec: v0.1.0-rc.2
    name: tf-serving
    registry: kubeflow
name: ks-app
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    gitVersion:
      commitSha: bb84329fd79c6dfead218c7348189df751700db6
      refSpec: v0.1.0-rc.2
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/v0.1.0-rc.2/kubeflow
version: 0.0.1
