apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: nfs-external
  namespace: kubeflow-test-infra  
spec:
  accessModes:
  - ReadWriteMany
  dataSource: null
  resources:
    requests:
      storage: 500Mi
  storageClassName: gcfs-storage
  volumeMode: Filesystem
  volumeName: gcfs
