apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  creationTimestamp: null
  name: kf-releasing-0-6-2
  namespace: kubeflow
spec:
  appdir: /home/jlewi/git_kubeflow-testing/release-infra/kf-releasing-0-6-2
  applications:
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: istio-system
      repoRef:
        name: manifests
        path: istio/istio-crds
    name: istio-crds
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: istio-system
      repoRef:
        name: manifests
        path: istio/istio-install
    name: istio-install
  - kustomizeConfig:
      parameters:
      - name: clusterRbacConfig
        value: "ON"
      repoRef:
        name: manifests
        path: istio/istio
    name: istio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/application-crds
    name: application-crds
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: application/application
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metacontroller
    name: metacontroller
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: argo
    name: argo
  - kustomizeConfig:
      overlays:
      - istio
      - application
      parameters:
      - name: userid-header
        value: X-Goog-Authenticated-User-Email
      - name: userid-prefix
        value: 'accounts.google.com:'
      repoRef:
        name: manifests
        path: common/centraldashboard
    name: centraldashboard
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: admission-webhook/webhook
    name: webhook
  - kustomizeConfig:
      parameters:
      - name: webhookNamePrefix
        value: admission-webhook-
      repoRef:
        name: manifests
        path: admission-webhook/bootstrap
    name: bootstrap
  - kustomizeConfig:
      overlays:
      - istio
      - application
      parameters:
      - name: userid-header
        value: X-Goog-Authenticated-User-Email
      - name: userid-prefix
        value: 'accounts.google.com:'
      repoRef:
        name: manifests
        path: jupyter/jupyter-web-app
    name: jupyter-web-app
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/katib-db
    name: katib-db
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/katib-manager
    name: katib-manager
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/katib-controller
    name: katib-controller
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: katib-v1alpha2/katib-ui
    name: katib-ui
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/metrics-collector
    name: metrics-collector
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: metadata
    name: metadata
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: katib-v1alpha2/suggestion
    name: suggestion
  - kustomizeConfig:
      overlays:
      - istio
      - application
      parameters:
      - name: injectGcpCredentials
        value: "true"
      repoRef:
        name: manifests
        path: jupyter/notebook-controller
    name: notebook-controller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pytorch-job/pytorch-job-crds
    name: pytorch-job-crds
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: pytorch-job/pytorch-operator
    name: pytorch-operator
  - kustomizeConfig:
      parameters:
      - initRequired: true
        name: usageId
        value: "168070786618016921"
      - initRequired: true
        name: reportUsage
        value: "true"
      repoRef:
        name: manifests
        path: common/spartakus
    name: spartakus
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: tensorboard
    name: tensorboard
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: tf-training/tf-job-operator
    name: tf-job-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/api-service
    name: api-service
  - kustomizeConfig:
      overlays:
      - minioPd
      parameters:
      - name: minioPd
        value: kf-releasing-0-6-2-storage-artifact-store
      - name: minioPvName
        value: minio-pv
      - name: minioPvcName
        value: minio-pv-claim
      repoRef:
        name: manifests
        path: pipeline/minio
    name: minio
  - kustomizeConfig:
      overlays:
      - mysqlPd
      parameters:
      - name: mysqlPd
        value: kf-releasing-0-6-2-storage-metadata-store
      - name: mysqlPvName
        value: mysql-pv
      - name: mysqlPvcName
        value: mysql-pv-claim
      repoRef:
        name: manifests
        path: pipeline/mysql
    name: mysql
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/persistent-agent
    name: persistent-agent
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/pipelines-runner
    name: pipelines-runner
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: pipeline/pipelines-ui
    name: pipelines-ui
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/pipelines-viewer
    name: pipelines-viewer
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: pipeline/scheduledworkflow
    name: scheduledworkflow
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: cert-manager/cert-manager-crds
    name: cert-manager-crds
  - kustomizeConfig:
      parameters:
      - initRequired: true
        name: acmeEmail
        value: jlewi@google.com
      repoRef:
        name: manifests
        path: cert-manager/cert-manager
    name: cert-manager
  - kustomizeConfig:
      parameters:
      - name: secretName
        value: admin-gcp-sa
      repoRef:
        name: manifests
        path: gcp/cloud-endpoints
    name: cloud-endpoints
  - kustomizeConfig:
      overlays:
      - istio
      parameters:
      - initRequired: true
        name: admin
        value: jlewi@google.com
      - name: userid-header
        value: X-Goog-Authenticated-User-Email
      - name: userid-prefix
        value: 'accounts.google.com:'
      repoRef:
        name: manifests
        path: profiles
    name: profiles
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: gcp/gpu-driver
    name: gpu-driver
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: istio-system
      - initRequired: true
        name: ipName
        value: kf-releasing-0-6-2-ip
      - initRequired: true
        name: hostname
        value: kf-releasing-0-6-2.endpoints.kubeflow-releasing.cloud.goog
      repoRef:
        name: manifests
        path: gcp/iap-ingress
    name: iap-ingress
  email: jlewi@google.com
  enableApplications: true
  hostname: kf-releasing-0-6-2.endpoints.kubeflow-releasing.cloud.goog
  ipName: kf-releasing-0-6-2-ip
  manifestsRepo: /home/jlewi/git_kubeflow-testing/release-infra/kf-releasing-0-6-2/.cache/manifests/manifests-56e2fb15db286198f7a53723cb1fbfecf3fe83fb
  packageManager: kustomize
  platform: gcp
  plugins:
  - name: gcp
    spec:
      auth:
        iap:
          oAuthClientId: 67369850431-atj9l5ti8hr6mltv9co9cd404kas7f09.apps.googleusercontent.com
          oAuthClientSecret:
            name: CLIENT_SECRET
      createPipelinePersistentStorage: true
  project: kubeflow-releasing
  repos:
  - name: kubeflow
    uri: https://github.com/kubeflow/kubeflow/archive/0dbd2550372c003ba69069aeee283bd59fb1341f.tar.gz
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/56e2fb15db286198f7a53723cb1fbfecf3fe83fb.tar.gz
  secrets:
  - name: CLIENT_SECRET
    secretSource:
      envSource:
        Name: CLIENT_SECRET
  serverVersion: file:bootstrap/k8sSpec/v1.11.7/api/openapi-spec/swagger.json
  skipInitProject: true
  useBasicAuth: false
  useIstio: true
  zone: us-east1-d
status:
  reposCache:
    kubeflow:
      localPath: '"/home/jlewi/git_kubeflow-testing/release-infra/kf-releasing-0-6-2/.cache/kubeflow/kubeflow-0dbd2550372c003ba69069aeee283bd59fb1341f"'
    manifests:
      localPath: '"/home/jlewi/git_kubeflow-testing/release-infra/kf-releasing-0-6-2/.cache/manifests/manifests-56e2fb15db286198f7a53723cb1fbfecf3fe83fb"'
